[project]
name = "graphical-sampling"
version = "0.1.0"
description = "Python package for Graphical Sampling Method"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.10.8",
    "numpy>=2.4.2",
    "scikit-learn>=1.8.0",
    "scipy>=1.17.1",
    "pandas>=3.0.1",
    "joblib>=1.5.3",
    "tqdm>=4.67.3",
    "numba>=0.64.0",
    "scipy-stubs~=1.17.1",
]
authors = [
    { name = "Bardia Panahbehagh", email = "bardia.panah@gmail.com" },
    { name = "Mehdi Mohebbi", email = "mehdi.mohebbi23@gmail.com" },
    { name = "AmirMohammad HosseiniNasab", email = "awmirhn@gmail.com" },
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "mypy>=1.13.0",
    "notebook>=7.2.2",
    "pytest>=8.3.4",
    "ruff>=0.7.1",
    "types-tqdm>=4.66.0.20240417",
]

[tool.hatch.build.targets.wheel]
packages = ["graphical_sampling"]

[tool.ruff]
extend-exclude = ["*.ipynb"]
